merge conflicts

diff --git a/samples/jenkins/Jenkinsfile b/samples/jenkins/Jenkinsfile
--- a/samples/jenkins/Jenkinsfile
+++ b/samples/jenkins/Jenkinsfile
@@ -519,6 +519,258 @@ line3'''
                 }
             }
         }
+        stage('Publish') {
+            steps {
+                s3Upload entries: [
+                [bucket: 'bucket-1', excludedFile: '2.txxt'
+                 , flatten: false, gzipFiles: false, keepForever: false
+                 , selectedRegion: 'us-west-1', showDirectlyInBrowser: false
+                 , sourceFile: '*.txt', uploadFromSlave: false],
+                [bucket: 'bucket-1'
+                 , flatten: false, gzipFiles: true, keepForever: false
+                 , selectedRegion: 'us-west-1', showDirectlyInBrowser: false
+                 , sourceFile: '*.md', uploadFromSlave: false]
+                ], profileName: 'default'
+            }
+        }
+        stage('Jacoco reports') {
+            steps {
+                jacoco(
+                        classPattern: '**/target/classes, **/WEB-INF/classes',
+                        exclusionPattern: '**/controllers/*.class',
+                        inclusionPattern: '**/*.class',
+                        sourceInclusionPattern: '**/*.java',
+                        sourceExclusionPattern: '**/controllers/*.java',
+                        maximumBranchCoverage: '81',
+                        maximumClassCoverage: '85',
+                        maximumComplexityCoverage: '10',
+                        maximumInstructionCoverage: '80',
+                        maximumLineCoverage: '83',
+                        maximumMethodCoverage: '84'
+                )
+            }
+        }
+        //Allure Jenkins pipeline stages
+        stage('Checkout') {
+            steps {
+                git branch: 'master', url: 'https://github.com/eroshenkoam/allure-example.git'
+            }
+        }
+        stage('Build') {
+            steps {
+                sh './gradlew clean test'
+            }
+        }
+        stage('Report') {
+            steps {
+                allure([
+                    includeProperties: false,
+                    jdk: '',
+                    properties: [],
+                    reportBuildPolicy: 'ALWAYS',
+                    results: [[path: 'build/allure-results']]
+                ])
+            }
+        }
+        stage('Run NUnit') {
+            steps {
+                script {
+                    def xmlFileUrl = 'https://raw.githubusercontent.com/harness-community/test-jenkins-to-harness/refs/heads/main/nunit-test-result.xml'
+                    def outputFilePath = 'TestResult.xml'
+
+                    bat """
+                    powershell -Command "Invoke-WebRequest -Uri '${xmlFileUrl}' -OutFile '${outputFilePath}'"
+                    """
+                }
+                nunit testResultsPattern: 'TestResult.xml', failIfNoResults: true, skipJUnitArchiver: false, failedTestsFailBuild: true
+            }
+        }
+        // Javadoc Steps
+        stage('Checkout') {
+            steps {
+                git url: 'https://github.com/spring-guides/gs-rest-service.git', branch: 'main'
+            }
+        }
+        stage('Build') {
+            steps {
+                sh 'cd complete && gradle clean build --info --stacktrace'
+            }
+        }
+        stage('Generate Javadoc') {
+            steps {
+                sh 'cd complete && gradle javadoc --info --stacktrace'
+            }
+        }
+        stage('Publish Javadoc') {
+            steps {
+                javadoc javadocDir: 'complete/build/docs/javadoc', keepAll: true
+            }
+        }    
+        //Kube-ctl
+        stage('Check Docker') {
+            steps {
+                sh '''
+                    echo "Current PATH: $PATH"
+                    which docker || echo "Docker not found"
+                '''
+            }
+        }
+        stage('Run Kubectl') {
+            steps {
+                withKubeConfig([
+                    credentialsId: 'credentialsId', // Replace with your actual credentials ID
+                    serverUrl: 'https://127.0.0.1:56227' // Replace with your actual server URL
+
+                ]) {
+                    sh 'kubectl get pods' // Run your kubectl command here
+                }
+            }
+        }
+        // Cobertura plugin stage begins
+        stage('Checkout sample code for Cobertura coverage.xml file') {
+            steps {
+                git branch: "main", url: "https://github.com/harness-community/drone-coverage-report.git"
+            }
+        }
+        stage('Publish Cobertura Coverage Report') {  // Cobetura plugin stage
+            steps {
+                cobertura coberturaReportFile: '**/coverage.xml',
+                        autoUpdateHealth: false,
+                        autoUpdateStability: false,
+                        failUnhealthy: false,
+                        failUnstable: false,
+                        lineCoverageTargets: '80, 0, 0',
+                        methodCoverageTargets: '80, 0, 0',
+                        classCoverageTargets: '70, 0, 0',
+                        conditionalCoverageTargets: '65, 0, 0'
+            }
+        }
+        // slackFileUpload plugin stage begins here
+        stage('Generate Temp File') {
+            steps {
+                script {
+                    def words = ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape']
+                    def randomWords = (1..5).collect { words[new Random().nextInt(words.size())] }.join(' ')
+                    writeFile file: 'b.txt', text: randomWords
+                    echo "Temp file created with content: ${randomWords}"
+                }
+            }
+        }
+        stage('Upload to Slack') {
+            steps {
+                slackUploadFile(
+                    channel: 'C07TL1KNV8Q',
+                    credentialId: 'SlackChannelCreds',
+                    failOnError: true,
+                    filePath: 'b.txt',
+                    initialComment: 'jenkins file upload test'
+                )
+            }
+        }
+        // slackSend plugin stage begins here
+        stage('Send Slack Notification') {
+            steps {
+                slackSend channel: 'dev',
+                          color: 'good',
+                          iconEmoji: ':rocket:',
+                          message: 'hi, the test msg slack now test ...',
+                          teamDomain: 'jenkins-bot-testing',
+                          tokenCredentialId: 'slackcreds03',
+                          username: 'jenkins-test-user'
+            }
+        }
+        // publishHTML plugin stage begins
+        stage('Generate HTML Reports') {
+            steps {
+                script {
+                    sh 'mkdir -p reports'
+                    writeFile file: 'reports/index.html', text: '''
+                        <html>
+                        <head><title>Sample Report</title></head>
+                        <body>
+                            <h1>Main Report</h1>
+                            <p>This is the main report page.</p>
+                        </body>
+                        </html>
+                    '''
+                }
+            }
+        }
+        stage('Publish HTML Report') {
+            steps {
+                publishHTML(target: [
+                        reportName : 'Sample HTML Report',
+                        reportDir  : 'reports',
+                        reportFiles: 'index.html',
+                        includes   : '**/*.html,**/*.css'
+                ])
+            }
+        }
+        //mailer
+        stage('Test') {
+            steps {
+                script {
+                    // Set the build result to test email notifications
+                    currentBuild.result = 'FAILED' // Change to 'UNSTABLE' or 'SUCCESS' as needed
+                }
+            }
+        }
+         post {
+            always {
+                mail(
+                    to: "test.uyser@testmail.com",
+                    subject: "Jenkins Build - ${currentBuild.fullDisplayName}",
+                    body: """
+                    Build Status: ${currentBuild.currentResult}
+                    Check console output at: ${env.BUILD_URL}console
+                    """
+                )
+            }
+        }
+        // nexusArtifactUploader plugin stage begins
+        stage('Generate File') {
+            steps {
+                writeFile file: 'fruit_names.txt', text: 'apple\nbanana\ncherry\ndate\nelderberry\nfig\ngrape\nhoneydew\nkiwi\nlemon'
+                echo "Generated file: fruit_names.txt"
+            }
+        }
+
+        stage('Upload to Nexus') {
+            steps {
+                nexusArtifactUploader artifacts: [[
+                    artifactId: 'fruit-names-v0.1',
+                    file: 'fruit_names.txt',
+                    type: 'txt'
+                ]],
+                credentialsId: 'nexus-hnstest01-creds',
+                groupId: 'test01',
+                nexusUrl: '4.24.1.21:9192/',
+                repository: 'plg01maven2',
+                version: '1.12'
+            }
+        }
+        //Nodejs conversion Step
+        stage('Install Packages') {
+            steps {
+                // Set up the NodeJS environment
+                nodejs(nodeJSInstallationName: 'node') {
+                    sh '''
+                        # Ensure npm uses the public registry
+                        echo "registry=https://registry.npmjs.org/" > .npmrc
+                        npm install
+                    '''
+                }
+            }
+        }
+
+        stage('Run Tests') {
+            steps {
+                nodejs(nodeJSInstallationName: 'node') {
+                    // Run npm test to execute the "test" script in package.json
+                    sh 'npm test'
+                }
+            }
+        }
         //Gatling
         stage('Checkout Code') {
             steps {
